### ISSUE TITLE
File is running but no output

### ISSUE THREAD

**Issue by iamkatha** [bntan/doctolib-covid#1]
Hi Bntan,

Thanks for creating this repository.
I have tried to run your file. As I am in Germany, I adapted it to doctolib.de. 
I have also changed the disabled password, receiver email, sender email and password, e.g. os.environ["SENDER_EMAIL"]= "xxx".

When running the file no output is created, but I also receive no error.

Do you have any inputs why?

Thanks a lot!

**Comment by bntan** [comment]
Hello @iamkatha,

Could you please tell us how you adapted the code to doctolib.de?
No output probably means no center corresponding to the search criteria.

You need to change the centers (centers.txt), the host "www.doctolib.fr" to "www.doctolib.de", but also adapt the "visit_motives" since mine is related to France. 

I have not tested, but here are 2 adaptions to doctolib.de:
- From @nosyjoe: https://github.com/nosyjoe/doctolib-covid
- From @amedhat3:  https://github.com/amedhat3/doctolib-covid

Hope this helps!

Regards,

Bun-Ny

**Comment by nosyjoe** [comment]
Hi,

so my version works for german doctolib when I run it on my local machine.

Unfortunately I could not get it to run on Github Actions, a got a 403 Forbidden for the network calls. I tried a different user agent but it did not help. I ended up running it on my Raspi instead, where it does not receive any 403s

@iamkatha have you checked the Github Actions output if you're getting the same error, or any other error for that matter?

@bntan thanks for creating the code btw!

**Comment by iamkatha** [comment]
Thank you both for your answer and sorry, for my late reply.

I had initally made these two suggestion (in doctolib.fr and changing visist_motives).
However, it did not seem to run (on my local machine).

@bntan thanks a lot for pointing out the two adaptations they worked for me.

Thanks a lot again!
